listening-port=3478
# Use 0.0.0.0 to listen on all interfaces inside the container
listening-ip=0.0.0.0 
# CRITICAL: This maps the internal Docker IP to your reachable Host IP
external-ip=<EXT_IP>/172.18.0.3

fingerprint
lt-cred-mech
realm=localhost
user=webrtc:webrtcpass

# Keep your restricted port range for easier Docker mapping
min-port=49160
max-port=49200
log-file=stdout